# Generated by Django 3.0.8 on 2020-11-11 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('wiki_terms', models.CharField(max_length=200)),
                ('wiki_text', models.TextField()),
                ('answer', models.CharField(max_length=200)),
                ('prediction_score', models.FloatField(default=0)),
            ],
        ),
    ]
